Mission04_cji23/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_cji23.Models
{
    public class GradeCalculatorModel
    {
        // assignments
        [Required]
        [Range(1,100)]
        public float Assignments { get; set; }
        //group
        [Required]
        [Range(1, 100)]
        public float Group { get; set; }
        // quizzes
        [Required]
        [Range(1, 100)]
        public float Quizzes { get; set; }
        // midterms
        [Required]
        [Range(1, 100)]
        public float Midterm { get; set; }
        // final
        [Required]
        [Range(1, 100)]
        public float Final { get; set; }
        // intex
        [Required]
        [Range(1, 100)]
        public float Intex { get; set; }
    }
}

Mission04_cji23/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_cji23.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_cji23.Controllers
{
    // pages controller
    public class PagesController : Controller
    {
        // index
        public IActionResult Index()
        {
            return View();
        }

        // grade calculator
        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        // grade calculator w/ model
        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission04_cji23/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" href="~/favfinal4.ico" type="image/x-icon" /> <!-- favicon -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Pages" asp-action="Index">Home</a>
        <a asp-controller="Pages" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>
    <div>
        @RenderBody()
    </div>

</body>
</html>